#!/bin/sh
set -eu

# Generate the LiteLLM model_list from the GGUFs in the shared model store.
#
# llama-server discovers models by scanning var/lib/llama at startup, but
# LiteLLM needs each one declared so that /v1/models is correct (the Open WebUI
# dropdown depends on it) and so per-model limits can be attached. A wildcard
# `model_name: "*"` entry would avoid this file but makes /v1/models return
# literally `*`, so this script keeps the two views in sync instead.
#
# One deployment is emitted per (model, router) pair: LiteLLM then load
# balances across the routers and cools a failing one out of rotation.
#
# This is the LiteLLM-side analogue of nginx/healthcheck.sh generating
# upstream.conf -- generated output lives under var/run/ and is gitignored.
#
# Usage:
#   ./litellm/gen-models.sh            # regenerate the model list
#   ./litellm/gen-models.sh --reload   # regenerate, then restart the routers
#                                      # and LiteLLM so it takes effect

REPO_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

MODELS_DIR="${MODELS_DIR:-$REPO_ROOT/var/lib/llama}"
OUT="${OUT:-$REPO_ROOT/var/run/litellm/models.generated.yaml}"

# Must match the service names in docker-compose.yml and their container port.
ROUTERS="${ROUTERS:-llama-1 llama-2}"
ROUTER_PORT="${ROUTER_PORT:-8080}"

# Cap in-flight requests per (model, router). Keep this equal to
# LLAMA_ARG_PARALLEL in docker-compose.yml: a loaded model has exactly that
# many slots, so anything beyond it only queues inside llama-server where
# LiteLLM can neither see it nor account for it.
MAX_PARALLEL="${MAX_PARALLEL:-2}"

RELOAD=0
case "${1:-}" in
  --reload) RELOAD=1 ;;
  '') ;;
  *) echo "usage: $0 [--reload]" >&2; exit 1 ;;
esac

[ -d "$MODELS_DIR" ] || { echo "error: model store not found: $MODELS_DIR (run ./setup.sh)" >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"
TMP="$OUT.tmp"

# Sharded GGUFs (foo-00001-of-00003.gguf) are not standalone models: neither
# llama-server's --models-dir scan nor this script can serve them directly, so
# skip every shard rather than emit one bogus model per file. Use
# LLAMA_ARG_MODELS_PRESET for those (see README).
is_shard() {
  case "$1" in
    *-[0-9][0-9][0-9][0-9][0-9]-of-[0-9][0-9][0-9][0-9][0-9]) return 0 ;;
    *) return 1 ;;
  esac
}

# Collect model IDs first so we can emit an explicit empty list when there are
# none -- a bare `model_list:` key parses as null and LiteLLM fails to start.
models=''
count=0
for f in "$MODELS_DIR"/*.gguf; do
  [ -f "$f" ] || continue
  base=$(basename "$f" .gguf)
  if is_shard "$base"; then
    echo "skip (sharded GGUF, needs LLAMA_ARG_MODELS_PRESET): $(basename "$f")" >&2
    continue
  fi
  models="$models$base
"
  count=$((count + 1))
done

{
  echo "# Generated by litellm/gen-models.sh -- DO NOT EDIT."
  echo "# Source: $MODELS_DIR"
  echo "# Regenerate with: ./litellm/gen-models.sh --reload"
  if [ "$count" -eq 0 ]; then
    echo "model_list: []"
  else
    echo "model_list:"
    echo "$models" | while IFS= read -r base; do
      [ -n "$base" ] || continue
      for router in $ROUTERS; do
        echo "  - model_name: \"$base\""
        echo "    litellm_params:"
        # The openai/ prefix tells LiteLLM to speak the OpenAI wire protocol;
        # the model name after it is what llama-server receives and matches
        # against its discovered GGUFs.
        echo "      model: \"openai/$base\""
        echo "      api_base: \"http://$router:$ROUTER_PORT/v1\""
        # llama-server has no auth of its own, but the OpenAI SDK inside
        # LiteLLM requires a non-empty key.
        echo "      api_key: \"none\""
        echo "      max_parallel_requests: $MAX_PARALLEL"
        echo "    model_info:"
        # Stable per-deployment id, so spend logs and the Admin UI show which
        # router actually served a request.
        echo "      id: \"$base@$router\""
        # Local inference is free. Declaring every cost field as zero keeps
        # spend logs at 0.00 and silences LiteLLM's "not in built-in cost map"
        # startup warning, which it emits once per deployment.
        echo "      input_cost_per_token: 0"
        echo "      output_cost_per_token: 0"
        echo "      cache_creation_input_token_cost: 0"
        echo "      cache_read_input_token_cost: 0"
      done
    done
  fi
} > "$TMP"

mv "$TMP" "$OUT"
echo "wrote $OUT ($count model(s) x $(set -- $ROUTERS; echo $#) router(s))"

if [ "$count" -eq 0 ]; then
  echo "warning: no .gguf files in $MODELS_DIR -- LiteLLM will start with an empty model list" >&2
fi

if [ "$RELOAD" -eq 1 ]; then
  echo "restarting routers and LiteLLM..."
  # The routers rescan var/lib/llama only at startup, and LiteLLM reads the
  # generated file only at startup, so both sides need the restart.
  (cd "$REPO_ROOT" && docker compose restart llama-1 llama-2 litellm)
fi
